@extends('layouts.app')
@section('title', 'Quản lý Blog')
@section('content')
<div class="admin-page-header">
    <div><div class="admin-page-kicker">Content studio</div><h1 class="admin-page-title"><i class="bi bi-newspaper text-primary me-2"></i>Blog / Tin tức</h1><p class="admin-page-subtitle">Tạo nội dung đẹp, quản lý nhanh và theo dõi trạng thái xuất bản.</p></div>
    <div class="d-flex gap-2"><a href="{{ route('admin.post-categories.index') }}" class="btn btn-light border rounded-3"><i class="bi bi-folder2-open me-1"></i>Danh mục</a><a href="{{ route('admin.posts.create') }}" class="btn btn-primary rounded-3 px-3"><i class="bi bi-plus-lg me-1"></i>Viết bài mới</a></div>
</div>
@if(session('success'))<div class="alert alert-success border-0 shadow-sm rounded-3">{{ session('success') }}</div>@endif
<div class="row g-3 mb-3"><div class="col-md-4"><div class="admin-stat-card"><span class="admin-stat-icon blue"><i class="bi bi-files"></i></span><div><div class="admin-stat-label">Tổng bài viết</div><div class="admin-stat-value">{{ $stats['total'] }}</div></div></div></div><div class="col-md-4"><div class="admin-stat-card"><span class="admin-stat-icon green"><i class="bi bi-check2-circle"></i></span><div><div class="admin-stat-label">Đã xuất bản</div><div class="admin-stat-value">{{ $stats['published'] }}</div></div></div></div><div class="col-md-4"><div class="admin-stat-card"><span class="admin-stat-icon gray"><i class="bi bi-pencil-square"></i></span><div><div class="admin-stat-label">Bản nháp</div><div class="admin-stat-value">{{ $stats['drafts'] }}</div></div></div></div></div>
<form class="admin-filter-bar row g-2 align-items-center mb-3" method="GET"><div class="col-lg-5"><div class="input-group"><span class="input-group-text bg-white border-end-0"><i class="bi bi-search text-muted"></i></span><input name="search" value="{{ request('search') }}" class="form-control border-start-0" placeholder="Tìm theo tiêu đề hoặc mô tả..."></div></div><div class="col-md-4 col-lg-2"><select name="status" class="form-select"><option value="">Mọi trạng thái</option><option value="published" @selected(request('status') === 'published')>Đã xuất bản</option><option value="draft" @selected(request('status') === 'draft')>Bản nháp</option></select></div><div class="col-md-4 col-lg-3"><select name="category" class="form-select"><option value="">Mọi chuyên mục</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) request('category') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="col-md-4 col-lg-2 d-flex gap-2"><button class="btn btn-dark flex-grow-1">Lọc</button><a href="{{ route('admin.posts.index') }}" class="btn btn-light border" title="Xóa bộ lọc"><i class="bi bi-arrow-counterclockwise"></i></a></div></form>
<div class="admin-table-card"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Bài viết</th><th>Chuyên mục</th><th>Trạng thái</th><th>Ngày đăng</th><th class="text-end">Thao tác</th></tr></thead><tbody>
@forelse($posts as $post)<tr><td><div class="d-flex align-items-center gap-3">@if($post->featured_image)<img src="{{ asset('storage/'.$post->featured_image) }}" class="admin-post-thumb" alt="">@else<span class="admin-post-placeholder"><i class="bi bi-image"></i></span>@endif<div><div class="fw-bold text-dark">{{ $post->title }}</div><small class="text-muted">/{{ $post->slug }}</small></div></div></td><td><span class="badge bg-light text-dark border">{{ $post->category?->name ?? 'Chưa phân loại' }}</span></td><td><span class="badge rounded-pill {{ $post->status === 'published' ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $post->status === 'published' ? 'Đã đăng' : 'Bản nháp' }}</span></td><td class="text-muted small">{{ $post->published_at?->format('d/m/Y H:i') ?? 'Chưa lên lịch' }}</td><td class="text-end text-nowrap"><a href="{{ route('posts.show', $post->slug) }}" target="_blank" class="btn btn-sm btn-light border" title="Xem ngoài trang"><i class="bi bi-box-arrow-up-right"></i></a><a href="{{ route('admin.posts.edit', $post) }}" class="btn btn-sm btn-outline-warning" title="Sửa"><i class="bi bi-pencil"></i></a><form action="{{ route('admin.posts.destroy', $post) }}" method="POST" class="d-inline" onsubmit="return confirm('Xóa bài viết này?');">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Xóa"><i class="bi bi-trash"></i></button></form></td></tr>
@empty<tr><td colspan="5" class="text-center text-muted py-5"><i class="bi bi-journal-x fs-2 d-block mb-2"></i>Không tìm thấy bài viết phù hợp.</td></tr>@endforelse
</tbody></table></div></div><div class="mt-3">{{ $posts->links() }}</div>
@endsection
